### ISSUE TITLE
Docker for Mac is not supported

### ISSUE THREAD

**Issue by mikaeleiman** [aerofs/aerofs-docker#10]
I had a look at the script and created a symlink from /ship to a dir in my user dir before running it, in the end it had this to say:

> Starting Loader...
> `+` docker start -a loader-1.4.11
> Error response from daemon: Mounts denied: docker-for-mac/osxfs/#namespaces for more info.
> .
> oader/run/tag and /ship/loader/run/target
> are not shared from OS X and are not known to Docker.
> You can configure shared paths from Docker -> Preferences... -> File Sharing.
> See https://docs.docker.com/

Using release version of Docker for macOS.

**Comment by mikaeleiman** [comment]
Added /ship to the Docker > Prefs > File sharing list, and then:

> ~/aerofs-docker> docker start -a loader-1.4.11
> `>>>` ['crane', 'run', 'maintenance', '-d', 'all', '-c', '/modified.yml']
> Running container data-1.4.11 ... 56710103e2e41c679c770226dfee5b15c493e699ca853f4f01fb03b5ee941d4c
> Running container config-1.4.11 ... c7b601d9baea8566906c01aa6149d749f3b4243bbe9c7f30b87065dad8f02734
> Running container maintenance-web-1.4.11 ... 67349c33a6ed244e94419942e5a24511e8ecbad2cc6605560b2c59b6f9f21161
> Running container mysql-1.4.11 ... 8acdf3147831a57f32ff89431836611ab30976ed0b2e9d5a4f16e6d42b448563
> Running container ca-server-1.4.11 ... 340ac6590c913374ab3a95bddfad453fcaac47e37049f358d06d7f6a3091135e
> Running container ntp-1.4.11 ... 9a71f72a443fc0071cfef71d56e8987569803048e6226004139dc825e966b2ed
> Running container postfix-1.4.11 ... e7c2d9a6adbe1672e6835d479e165b2d54cc79c70eb856574386093cbe958932
> Running container repackaging-1.4.11 ... abc8ad5ff2692a238c9e6c89b2e3891d8b84328ad4d7a963d82bea3267143f66
> Running container verification-1.4.11 ... 9790f6c88324ee3605f103554ccc3f603518a8284daa15503a1da64f72697667
> Running container maintenance-bunker-1.4.11 ... f264718922f3d06f02f086003fff073907a93e9d530f896b3e53e1494e5dad04
> Running container maintenance-nginx-1.4.11 ... b1eca40c53a2407c7450f58e7a935420123988580f13e111a07282e6d603b12e
> time="2016-07-29T09:34:46Z" level="fatal" msg="Error response from daemon: driver failed programming external connectivity on endpoint maintenance-nginx-1.4.11 (ee57b1a80b24257548ac1a0b792203b93135d60bbf9f2122360e07971fdb7a1d): Error starting userland proxy: Bind for 0.0.0.0:443: unexpected error (Failure EADDRINUSE)" 
> ERROR: exit status 1
> Traceback (most recent call last):
>   File "/main.py", line 107, in <module>
>     main()
>   File "/main.py", line 58, in main
>     loader.load(argv[2], argv[3], argv[4])
>   File "/loader.py", line 25, in load
>     call_crane('run', target)
>   File "/common.py", line 20, in call_crane
>     subprocess.check_call(print_args(args))
>   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['crane', 'run', 'maintenance', '-d', 'all', '-c', '/modified.yml']' returned non-zero exit status 1

I'm guessing that it's trying to use the same port my already-existing web server is using.

**Comment by huguesb** [comment]
At this time we only officially support Linux hosts. Please consider using docker-machine until we announce support for Docker for Mac.

AeroFS publishes [multiple ports](https://support.aerofs.com/hc/en-us/articles/204624454)  and containers will fail to start if they are already taken.
