### ISSUE TITLE
aerofs-docker.sh does not work with CentOS 7

### ISSUE THREAD

**Issue by ghost** [aerofs/aerofs-docker#11]
**Synopsis**
I tried to run aerofs-docker.sh on CentOS 7 (detailed info below). I receive the following error:

**Stacktrace**
registry.aerofs.com/aerofs/loader: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
Get http:///var/run/docker.sock/v1.17/images/693fba44a802/json: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?Traceback (most recent call last):
  File "/main.py", line 107, in <module>
    main()
  File "/main.py", line 36, in main
    for i in loader.get_images():
  File "/loader.py", line 31, in get_images
    containers = load_crane_yml()['containers']
  File "/crane_yml.py", line 21, in load_crane_yml
    crane_yml = render_crane_yml(CRANE_JINJA_PATH, my_subdomain())
  File "/common.py", line 81, in my_subdomain
    prefix = my_container_prefix()
  File "/common.py", line 71, in my_container_prefix
    m = match("^(.*-hpc-)loader", my_container_name())
  File "/common.py", line 60, in my_container_name
    my_container_id()]).strip('/ \n\t\r')
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['docker', 'inspect', '-f', '{{ .Name }}', '693fba44a802']' returned non-zero exit status 1

**Docker info**
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
 Go version:      go1.6.3
 Git commit:      d381c64-unsupported
 Built:           Thu Aug  4 13:21:17 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
 Go version:      go1.6.3
 Git commit:      d381c64-unsupported
 Built:           Thu Aug  4 13:21:17 2016
 OS/Arch:         linux/amd64

**OS Info**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by huguesb** [comment]
The shell scripts expects the docker daemon to be reachable via Unix Domain Socket at the standard `/var/run/docker.sock` path. If the docker daemon doesn't expose this socket interface or if the calling user cannot access it the script will fail.
