### ISSUE TITLE
Warnings about legacy registry during installation

### ISSUE THREAD

**Issue by mikaeleiman** [aerofs/aerofs-docker#9]
I'm getting a bunch of messages like this:

> registry.aerofs.com/aerofs/maintenance-nginx:
> 
> this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.

Is this a cause for concern? I'm using the release version of Docker for macOS.

**Comment by huguesb** [comment]
We are still using docker registry v1 because the newer version doesn't work properly for us.

https://github.com/docker/distribution/issues/1411

We'll eventually upgrade when this issue is fixed.
